services:
  dash:
    image: mauricenino/dashdot
    container_name: dashdot
    privileged: true
    ports:
      - "85:3001"
    environment:
      - DASHDOT_WIDGET_LIST=os,cpu,storage,ram,network
      - DASHDOT_PAGE_TITLE=iroha
      - DASHDOT_DISABLE_INTEGRATIONS=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_CUSTOM_HOST=iroha
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_FS_DEVICE_FILTER=mmcblk0
      - DASHDOT_OVERRIDE_STORAGE_TYPES=sda=SSD
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_NETWORK_SPEED_AS_BYTES=true
    volumes:
      - /:/mnt/host:ro 
    restart: unless-stopped 
