services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./assets:/www/assets
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 1m
      timeout: 3s
