services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    ports:
      - "85:8090"
    volumes:
      - ./beszel_data:/beszel_data
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /mnt/ssd:/extra-filesystems/WD_Green_SSD:ro
    environment:
      LISTEN: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGSDMJrjaSxRsFWXr2/SN1EvBi4pR09xoJZoi0199SAm'
      TOKEN: 1cafd-179e06745-1eae8-7073823e4
      HUB_URL: http://192.168.68.4:85
