---
# Main Settings
title: "Iroha Dashboard"
subtitle: "Raspberry Pi Zero 2 W"
logo: "assets/tools/iroha.png"
header: true
footer: false
connectivityCheck: true # Pings endpoints to see if they are alive

colors:
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#e1e1e1"
    link-hover: "#ffdd57"

services:
  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - name: "Pi-hole"
        logo: "assets/tools/pihole.png"
        subtitle: "Ad-Blocker and DNS provider"
        url: "http://192.168.68.4:81/admin" # CHANGE THIS IP
        target: "_blank"

      - name: "TTYD"
        icon: "fas fa-terminal"
        subtitle: "Terminal Access"
        url: "http://192.168.68.4:7681" # CHANGE THIS IP
        target: "_blank"

      - name: "File Browser"
        logo: "assets/tools/filebrowser.png"
        subtitle: "File Browser"
        url: "http://192.168.68.4:82" # CHANGE THIS IP
        target: "_blank"

  - name: "Network"
    icon: "fas fa-download"
    items:
      - name: "Transmission"
        logo: "/assets/tools/transmission.png"
        subtitle: "Torrent Client"
        url: "http://192.168.68.4:9091" # CHANGE THIS IP
        target: "_blank"

      - name: "WireGuard"
        logo: "/assets/tools/wireguard.png"
        subtitle: "VPN Tunnel"
        url: "http://192.168.68.4:51821" # CHANGE THIS IP
        target: "_blank"
